### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by bacdillon** [Fred-Barclay/Termination#54] opened 2017-07-08 12:18 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [termination](https://github.com/Fred-Barclay/Termination) package 0.5.1

### Stack Trace

Uncaught Error: channel closed

```
At events.js:160

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.18.0/resources/app/src/task.js:119:33)
    at TerminationView.module.exports.TerminationView.resize (/packages/termination/lib/view.coffee:268:17)
    at TerminationView.module.exports.TerminationView.resizeTerminalToView (/packages/termination/lib/view.coffee:483:6)
    at TerminationView.module.exports.TerminationView.focus (/packages/termination/lib/view.coffee:446:6)
    at TerminationView.focus (/packages/termination/lib/view.coffee:1:1)
    at /packages/termination/lib/view.coffee:76:12)
    at HTMLDivElement.dispatch (/packages/termination/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/termination/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:24.8.0 fuzzy-finder:toggle-file-finder (div.tool-panel.tree-view)
     -3:21.1.0 editor:consolidate-selections (input.hidden-input)
     -3:21.1.0 core:cancel (input.hidden-input)
     -1:29.5.0 window:decrease-font-size (div.tool-panel.tree-view)
     -0:49 termination:toggle (div.tool-panel.tree-view)
  9x -0:48.8.0 window:decrease-font-size (div.tool-panel.tree-view)
```

### Non-Core Packages

```
language-powershell 4.0.0 
termination 0.5.1 
```

**Comment by Fred-Barclay** [comment] 2017-09-24 20:06
I can't reproduce this. Closing for now - @bacdillon does this still occur with the latest Atom and termination (currently v0.6.0)?

**Closed by Fred-Barclay** 2017-09-24 20:06 UTC

**Comment by xavalex** [comment] 2018-05-27 15:42
Hi, I still have this issue with Atom 1.27.1 x64 and Termination 0.6.2. I also have it with the Platformio-ide-terminal package actually.
