### ISSUE TITLE
Problem with electron launch from within atom using Termination

### ISSUE THREAD

**Issue by Devhercule** [Fred-Barclay/Termination#55] opened 2017-07-25 16:38 UTC
Hi,

It is impossible to launch my Electron application using your package "Termination" within atom, I have this error message:

```
PS D:\electron\MyProject> npm start

> MyProject@1.0.0 start D:\electron\MyProject
> electron .

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MyProject@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the DLWEB-Browser@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2017-07-25T15_41_03_909Z-debug.log
```

However, when I launch the same project on Windows PowerShell, it works properly.

I tried to launch the Quick Start example given in https://electron.atom.io/docs/tutorial/quick-start/

Same problem, impossible to run it from the atom terminal.

I tried with `unset ELECTRON_RUN_AS_NODE` but still not working

can you help me fix this error? 

Thank you

**Comment by Fred-Barclay** [comment] 2017-07-27 02:44
Duplicate of #11 #33 #35

**Comment by Fred-Barclay** [comment] 2017-07-27 03:02
Hi @Devhercule and thanks for trying Termination!
It's a known bug with Windows machines (it used to be problematic for Linux and macOS as well but we were able to fix that) - see, for instance, https://github.com/platformio/platformio-atom-ide-terminal/pull/184#issuecomment-283343069. The error appears to come from pty.js, which we use as a backend.

Unfortunately I don't have the time or resources to debug pty.js or contribute changes back up to it right now. 😢 Certainly I'd love to get it fixed some day. 

( @pbario has possibly gotten a fix in https://github.com/platformio/platformio-atom-ide-terminal/issues/112#issuecomment-283437247 but it requires python to be installed... maybe we could keep an eye on that?)

**Comment by Devhercule** [comment] 2017-07-27 07:14
Thank you @Fred-Barclay for your reply,

In the comment you mentioned, i tried this link given by @pbarbiero : 

> I can make a pull, but all I did was change pty.js to node-pty and included it instead of pty.js from process.coffee (see https://github.com/PhillMcKraken/platformio-atom-ide-terminal/commit/5653f119d225f09cd6053d5b9ea1b267542a228c) -- the issue here is that requires everyone to have python2.8 installed on their machine (everything else seems to be already included with the apm processes) I noticed you did some prebuild work with pty.js, that would have to be done for this as well.

But the link doesn't work...

**Comment by Fred-Barclay** [comment] 2019-01-20 04:30
Closing -- please see comments in https://github.com/Fred-Barclay/Termination/issues/33#issuecomment-455836813. We now use `node-pty-prebuilt` so this shouldn't be an issue.

**Closed by Fred-Barclay** 2019-01-20 04:30 UTC
Labels: Windows, bug, duplicate
